dist: trusty
sudo: required

language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libtool pkg-config asciidoc
  - sudo apt-get install -y libortp-dev libsndfile1-dev libtwolame-dev libsamplerate0-dev

script:
  - ./autogen.sh
  - make
