dist: trusty
sudo: required

language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libtool pkg-config
  - sudo apt-get install -y asciidoctor xmlto
  - sudo apt-get install -y libsndfile1-dev libsamplerate0-dev

script:
  - ./autogen.sh
  - make check
